/**
 * useAgents — data hooks for the Agents resource
 *
 * Standard CRUD is generated by createResourceHooks.
 * useToggleAgent is a custom PATCH endpoint, kept as a standalone hook.
 */

import { useMutation, useQueryClient } from '@tanstack/react-query'
import type { Agent } from '@/types'
import api from '@/lib/api'
import { createResourceHooks } from './useResource'

const { useList, useDetail, useCreate, useUpdate, useDelete, KEY } =
  createResourceHooks<Agent>({ key: 'agents', endpoint: '/agents', label: 'Agent' })

export const useAgents      = useList
export const useAgent       = useDetail
export const useCreateAgent = useCreate
export const useUpdateAgent = useUpdate
export const useDeleteAgent = useDelete

/** Toggle an agent's is_active flag via PATCH /agents/:id/toggle. */
export function useToggleAgent() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) => api.patch(`/agents/${id}/toggle`).then((r) => r.data),
    onSuccess: () => qc.invalidateQueries({ queryKey: KEY }),
  })
}
