/**
 * useConnections — data hooks for the Connections resource
 *
 * List / create / delete are generated by createResourceHooks.
 * Connections have no update endpoint, and useTestConnection
 * is a custom mutation kept as a standalone hook.
 */

import { useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import type { Connection } from '@/types'
import api from '@/lib/api'
import { createResourceHooks } from './useResource'

const { useList, useCreate, useDelete, KEY } =
  createResourceHooks<Connection>({ key: 'connections', endpoint: '/connections', label: 'Connection' })

export const useConnections      = useList
export const useCreateConnection = useCreate
export const useDeleteConnection = useDelete

/** Test a connection's credentials via POST /connections/:id/test. */
export function useTestConnection() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) =>
      api.post(`/connections/${id}/test`).then((r) => r.data) as Promise<{ success: boolean; status: string }>,
    onSuccess: (data) => {
      qc.invalidateQueries({ queryKey: KEY })
      if (data.success) toast.success('Connection is working')
      else toast.error('Connection test failed')
    },
    onError: () => toast.error('Connection test failed'),
  })
}
