/**
 * useConnections — data hooks for the Connections resource
 *
 * List / create / delete are generated by createResourceHooks.
 * Connections have no update endpoint, and useTestConnection
 * is a custom mutation kept as a standalone hook.
 *
 * useConnectCatalogItem is the merged former "Plugins" connect flow — it used
 * to POST to /plugins/{key}/connect on a separate router. Both wrote into the
 * same `connections` table, so they're one endpoint now (POST /connections/),
 * driven by the plugin catalogue (see backend/app/services/plugins.py) for
 * every type, GitHub/GitLab/Jira/Linear included, not just the ~35 that used
 * to only be reachable through the Plugins page.
 */

import { useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import type { Connection } from '@/types'
import api, { getApiError } from '@/lib/api'
import { createResourceHooks } from './useResource'

const { useList, useCreate, useDelete, KEY } =
  createResourceHooks<Connection>({ key: 'connections', endpoint: '/connections', label: 'Connection' })

export const useConnections      = useList
export const useCreateConnection = useCreate
export const useDeleteConnection = useDelete

/** Test a connection's credentials via POST /connections/:id/test. */
export function useTestConnection() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) =>
      api.post(`/connections/${id}/test`).then((r) => r.data) as Promise<{ success: boolean; status: string; detail?: string }>,
    onSuccess: (data) => {
      qc.invalidateQueries({ queryKey: KEY })
      if (data.success) toast.success(data.detail || 'Connection is working')
      else toast.error(data.detail || 'Connection test failed')
    },
    onError: () => toast.error('Connection test failed'),
  })
}

/** Connect any catalogue entry — GitHub/GitLab/Jira/Linear plus everything
 *  else in app/services/plugins.py — via the unified POST /connections/. */
export function useConnectCatalogItem() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: ({ type, ...body }: {
      type: string; name?: string; access_token?: string; workspace_url?: string;
      email?: string; extra?: string
    }) => api.post('/connections/', { type, ...body }).then((r) => r.data as Connection),
    onSuccess: (conn) => {
      qc.invalidateQueries({ queryKey: KEY })
      qc.invalidateQueries({ queryKey: ['integrations', 'plugins'] })
      const detail = conn.metadata?.verified_detail as string | undefined
      const displayName = conn.metadata?.display_name as string | undefined
      // A failed verification still created the connection, so this is a
      // warning rather than an error — the token is saved and can be fixed in
      // place instead of retyping the whole form.
      if (conn.status === 'connected') {
        toast.success(`${conn.name} connected${displayName ? ` as ${displayName}` : ''}`)
      } else {
        toast.warning(`Saved, but not verified — ${detail ?? 'check the credential'}`)
      }
    },
    onError: (e) => toast.error(getApiError(e, 'Could not connect that integration')),
  })
}
