/**
 * usePersonas — data hooks for the Persona resource.
 * Standard CRUD generated by createResourceHooks, same pattern as useSkills.ts.
 */

import type { Persona } from '@/types/simulation'
import { createResourceHooks } from './useResource'

const { useList, useDetail, useCreate, useUpdate, useDelete } =
  createResourceHooks<Persona>({ key: 'personas', endpoint: '/personas', label: 'Persona' })

export const usePersonas      = useList
export const usePersona       = useDetail
export const useCreatePersona = useCreate
export const useUpdatePersona = useUpdate
export const useDeletePersona = useDelete
