/**
 * useProjects — data hooks for the Projects resource
 *
 * Standard CRUD is generated by createResourceHooks.
 * useArchiveProject, useConnectionRepos, and useConnectionJiraProjects
 * are custom hooks kept as standalones.
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import type { Project } from '@/types'
import api from '@/lib/api'
import { createResourceHooks } from './useResource'

const { useList, useDetail, useCreate, useUpdate, useDelete, KEY } =
  createResourceHooks<Project>({ key: 'projects', endpoint: '/projects', label: 'Project' })

export const useProjects      = useList
export const useProject       = useDetail
export const useCreateProject = useCreate
export const useUpdateProject = useUpdate
export const useDeleteProject = useDelete

// ─── Shared payload types ────────────────────────────────────────────────────

export interface DeployTargetInput {
  env: string
  branch: string
}

export interface ProjectFormData {
  name: string
  description?: string
  type?: string
  repo_connection_id?: string | null
  repo_name?: string | null
  jira_connection_id?: string | null
  jira_project_key?: string | null
  pod_id?: string | null
  context_md?: string
  deploy_targets: DeployTargetInput[]
}

// ─── Custom hooks ────────────────────────────────────────────────────────────

/** Archive a project via PATCH /projects/:id/archive. */
export function useArchiveProject() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) => api.patch(`/projects/${id}/archive`).then((r) => r.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: KEY })
      toast.success('Project archived')
    },
    onError: () => toast.error('Failed to archive project'),
  })
}

/** Fetch repos for a GitHub/GitLab connection (used in the project wizard). */
export function useConnectionRepos(connectionId: string | null) {
  return useQuery<{ name: string; full_name: string }[]>({
    queryKey: ['connection-repos', connectionId],
    queryFn: () => api.get(`/connections/${connectionId}/repos`).then((r) => r.data),
    enabled: !!connectionId,
  })
}

/** Fetch Jira projects for a Jira connection (used in the project wizard). */
export function useConnectionJiraProjects(connectionId: string | null) {
  return useQuery<{ key: string; name: string; id: string }[]>({
    queryKey: ['connection-jira-projects', connectionId],
    queryFn: () => api.get(`/connections/${connectionId}/projects`).then((r) => r.data),
    enabled: !!connectionId,
  })
}
