/**
 * usePods — data hooks for the Pods resource
 *
 * Standard CRUD is generated by createResourceHooks.
 * useDuplicatePod hits a custom POST endpoint, kept as a standalone hook.
 */

import { useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import type { Pod } from '@/types'
import api from '@/lib/api'
import { createResourceHooks } from './useResource'

const { useList, useDetail, useCreate, useUpdate, useDelete, KEY } =
  createResourceHooks<Pod>({ key: 'pods', endpoint: '/pods', label: 'Pod' })

export const usePods      = useList
export const usePod       = useDetail
export const useCreatePod = useCreate
export const useUpdatePod = useUpdate
export const useDeletePod = useDelete

// Re-export the PodAgentInput type used in create/update payloads.
export interface PodAgentInput {
  agent_id: string
  execution_order: number
  count: number
  on_failure: string
  max_retries: number
}

/** Duplicate a pod and all its agent bindings via POST /pods/:id/duplicate. */
export function useDuplicatePod() {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) => api.post(`/pods/${id}/duplicate`).then((r) => r.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: KEY })
      toast.success('Pod duplicated')
    },
    onError: () => toast.error('Failed to duplicate pod'),
  })
}
