/**
 * useSkills — data hooks for the Skills resource
 *
 * Standard CRUD is generated by createResourceHooks.
 * Re-exported with domain-specific names so call sites don't change.
 */

import type { Skill } from '@/types'
import { createResourceHooks } from './useResource'

const { useList, useDetail, useCreate, useUpdate, useDelete } =
  createResourceHooks<Skill>({ key: 'skills', endpoint: '/skills', label: 'Skill' })

export const useSkills      = useList
export const useSkill       = useDetail
export const useCreateSkill = useCreate
export const useUpdateSkill = useUpdate
export const useDeleteSkill = useDelete
